USE [master]
GO
/****** TODO: FILEPATH PARAMETRIZATION ******/
/****** Object:  Database [cars]    Script Date: 01.01.2019 15:02:20 ******/
CREATE DATABASE [cars]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cars', FILENAME = N'C:\repos\studia\sbo_projekt\cars1.mdf', SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cars_log', FILENAME = N'C:\repos\studia\sbo_projekt\cars1_log.ldf', SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [cars] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cars].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cars] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cars] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cars] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cars] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cars] SET ARITHABORT OFF 
GO

ALTER DATABASE [cars] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cars] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cars] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cars] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cars] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cars] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cars] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cars] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cars] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cars] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cars] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cars] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cars] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cars] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cars] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cars] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cars] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cars] SET RECOVERY FULL 
GO

ALTER DATABASE [cars] SET  MULTI_USER 
GO

ALTER DATABASE [cars] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cars] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cars] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cars] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [cars] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [cars] SET QUERY_STORE = OFF
GO

ALTER DATABASE [cars] SET  READ_WRITE 
GO

